name: Liquibase Test Harness

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  liquibase-test-harness:
    uses: liquibase/build-logic/.github/workflows/lth-docker.yml@main
    secrets: inherit
