name: Build, Test, and Prepare Release Candidate

on:
  pull_request:
    types:
      - labeled
      - reopened
      - synchronize

jobs:
  integration-tests:
    name: Java ${{ matrix.java }}, YugabyteDB ${{ matrix.yugabyte }}
    runs-on: ubuntu-latest
    if: contains( github.event.pull_request.labels.*.name, 'Extension Release Candidate :rocket:' )
    strategy:
      matrix:
        java: [8, 11, 16]
        yugabytedb: [2.7.1.1-b1]
    services:
      yubabyte:
        image: yugabytedb/yugabyte:${{ matrix.yugabytedb }}
        env:
          POSTGRES_USER: lbtest
          POSTGRES_PASSWORD: lbtest
        ports:
          - 5433:5433
        volumes:
          - /home/runner/work/liquibase-yugabytedb/liquibase-yugabytedb/src/test/resources/docker/yugabytedb-init.sql:/docker-entrypoint-initdb.d/yugabytedb-init.sql
    steps:
      - uses: actions/checkout@v2
      - name: Cache Local Maven Repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'
      - name: Test With Maven
        run: mvn clean verify --file pom.xml
