name: Build, Test, and Prepare Release Candidate

on:
  pull_request:
    types:
      - labeled
      - reopened
      - synchronize

jobs:
  integration-tests:
    name: Java ${{ matrix.java }}, YugabyteDB ${{ matrix.yugabyte }}
    runs-on: ubuntu-latest
    if: contains( github.event.pull_request.labels.*.name, 'Extension Release Candidate :rocket:' )
    strategy:
      matrix:
        java: [8, 11, 16]
        yugabytedb: [2.7.1.1-b1]
    services:
      yubabyte:
        image: yugabytedb/yugabyte:${{ matrix.yugabytedb }}
        env:
          POSTGRES_USER: lbtest
          POSTGRES_PASSWORD: lbtest
        ports:
          - 5433:5433
          - 7000:7000
          - 9000:9000
          - 9042:9042
# docker run -d --name yugabyte  -p7000:7000 -p9000:9000 -p5433:5433 -p9042:9042\
#  yugabytedb/yugabyte:latest bin/yugabyted start\
#  --daemon=false
    steps:
      - uses: actions/checkout@v2
      - name: Cache Local Maven Repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'
      - name: Test With Maven
        run: mvn clean verify --file pom.xml
